name: 'Destroy Terraform Infrastructure'

on:

    workflow_dispatch:

permissions:
    id-token: write # This is required for Github Actions to request JWT
    contents: read # This is required for actions checkout
    pull-requests: write

jobs:
    
    destroy-terraform:
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash
                working-directory: .
        
        steps:

            - name: Copy repository code
              uses: actions/checkout@v4

            - name: Configure OIDC connection
              uses: aws-actions/configure-aws-credentials@v1
              with:
                role-to-assume: ${{secrets.AWS_ROLE}}
                role-session-name: GITHUB-ACTIONS-OIDC
                aws-region: us-east-1
            
            - name: install terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.2.5

            - name: Initialize Terraform
              id: init
              env:
                AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
                AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
              run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}"
        

            - name: destroy terraform
              id: destroy
              run: terraform destroy --auto-approve